.TH "colorMap_item" 3 "Wed Nov 30 2011" "Version V1.04" "VisDaVol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorMap_item \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transf.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBg\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "int \fBalfa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file transf.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBcolorMap_item::alfa\fP"
.PP
Definition at line 16 of file transf.h.
.SS "int \fBcolorMap_item::b\fP"
.PP
Definition at line 15 of file transf.h.
.SS "int \fBcolorMap_item::g\fP"
.PP
Definition at line 15 of file transf.h.
.SS "int \fBcolorMap_item::r\fP"
.PP
Definition at line 15 of file transf.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for VisDaVol from the source code.
