.TH "/home/aahmgbr/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/workspace/cube/src/glsl.h" 3 "Mon Nov 28 2011" "Version V1.04" "VisDaVol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aahmgbr/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/workspace/cube/src/glsl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <GL/glew.h>\fP
.br
\fC#include <GL/glut.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtextFileRead\fP (char *fn)"
.br
.ti -1c
.RI "int \fBtextFileWrite\fP (char *fn, char *s)"
.br
.ti -1c
.RI "void \fBprintShaderInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBprintProgramInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBsetShaders\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printProgramInfoLog (GLuint obj)"
.SS "void printShaderInfoLog (GLuint obj)"
.SS "void setShaders (void)"
.SS "char* textFileRead (char * fn)"
.SS "int textFileWrite (char * fn, char * s)"
.SH "Author"
.PP 
Generated automatically by Doxygen for VisDaVol from the source code.
