.TH "/home/agnus/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/git/VisDaVol/cube/src/glsl.cpp" 3 "Wed Nov 30 2011" "Version V1.04" "VisDaVol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/agnus/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/git/VisDaVol/cube/src/glsl.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'glsl.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtextFileRead\fP (char *fn)"
.br
.ti -1c
.RI "int \fBtextFileWrite\fP (char *fn, char *s)"
.br
.ti -1c
.RI "void \fBprintShaderInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBprintProgramInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBsetShaders\fP (GLuint *\fBp\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "GLuint \fBv\fP"
.br
.ti -1c
.RI "GLuint \fBf\fP"
.br
.ti -1c
.RI "GLuint \fBf2\fP"
.br
.ti -1c
.RI "GLuint \fBp\fP"
.br
.ti -1c
.RI "GLuint \fBg\fP"
.br
.ti -1c
.RI "int \fBgw\fP"
.br
.ti -1c
.RI "int \fBgh\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printProgramInfoLog (GLuint obj)"
.PP
Definition at line 88 of file glsl.cpp.
.SS "void printShaderInfoLog (GLuint obj)"
.PP
Definition at line 69 of file glsl.cpp.
.SS "void setShaders (GLuint * p)"
.PP
Definition at line 107 of file glsl.cpp.
.SS "char* textFileRead (char * fn)"
.PP
Definition at line 17 of file glsl.cpp.
.SS "int textFileWrite (char * fn, char * s)"
.PP
Definition at line 50 of file glsl.cpp.
.SH "Variable Documentation"
.PP 
.SS "GLuint \fBf\fP"
.PP
Definition at line 11 of file glsl.cpp.
.SS "GLuint \fBf2\fP"
.PP
Definition at line 11 of file glsl.cpp.
.SS "GLuint \fBg\fP"
.PP
Definition at line 11 of file glsl.cpp.
.SS "int \fBgh\fP"
.PP
Definition at line 12 of file glsl.cpp.
.SS "int \fBgw\fP"
.PP
Definition at line 12 of file glsl.cpp.
.SS "GLuint \fBp\fP"
.PP
Definition at line 11 of file glsl.cpp.
.SS "GLuint \fBv\fP"
.PP
Definition at line 11 of file glsl.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for VisDaVol from the source code.
