.TH "/home/aahmgbr/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/workspace/cube/src/glsl.cpp" 3 "Mon Nov 28 2011" "Version V1.04" "VisDaVol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aahmgbr/Dropbox/unicamp/disciplinas/IA369/MeusProgramas/workspace/cube/src/glsl.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'glsl.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtextFileRead\fP (char *fn)"
.br
.ti -1c
.RI "int \fBtextFileWrite\fP (char *fn, char *s)"
.br
.ti -1c
.RI "void \fBprintShaderInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBprintProgramInfoLog\fP (GLuint obj)"
.br
.ti -1c
.RI "void \fBsetShaders\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "GLuint \fBv\fP"
.br
.ti -1c
.RI "GLuint \fBf\fP"
.br
.ti -1c
.RI "GLuint \fBf2\fP"
.br
.ti -1c
.RI "GLuint \fBp\fP"
.br
.ti -1c
.RI "GLuint \fBg\fP"
.br
.ti -1c
.RI "int \fBgw\fP"
.br
.ti -1c
.RI "int \fBgh\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printProgramInfoLog (GLuint obj)"
.SS "void printShaderInfoLog (GLuint obj)"
.SS "void setShaders (void)"
.SS "char* textFileRead (char * fn)"
.SS "int textFileWrite (char * fn, char * s)"
.SH "Variable Documentation"
.PP 
.SS "GLuint \fBf\fP"
.SS "GLuint \fBf2\fP"
.SS "GLuint \fBg\fP"
.SS "int \fBgh\fP"
.SS "int \fBgw\fP"
.SS "GLuint \fBp\fP"
.SS "GLuint \fBv\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for VisDaVol from the source code.
